##############################
### WINDOWS AND WORKSPACES ###
##############################

# Suprimir maximizar en cualquier ventana
windowrule = suppress_event maximize, match:class .*

# Evitar foco en ventanas XWayland flotantes sin clase/título (fix típico de tooltips)
windowrule = no_focus on, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Picture-in-Picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$

# Calculadora
windowrule = float on, match:title Calculadora

# KeePassXC
windowrule = float on, match:class ^org\.keepassxc\.KeePassXC$
windowrule = size 800 600, match:class ^org\.keepassxc\.KeePassXC$
windowrule = center on, match:class ^org\.keepassxc\.KeePassXC$


windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
